import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({ selector: 'bsg-contact-page', standalone: true, imports: [FormsModule, CommonModule], template: `
<section class="page-hero container"><p class="eyebrow">Start a conversation</p><h1>Have an idea<br><em>worth building?</em></h1><p class="page-lead">Tell us what you are trying to create, improve or explore. You will speak directly with the founder behind BSG.</p></section>
<section class="container contact-layout"><div class="contact-note"><p class="eyebrow">Let’s talk about</p><h2>A website. A product idea. A better way forward.</h2><p>Whether you have a full brief or only the beginning of an idea, the first step is a straightforward conversation.</p><a href="mailto:info@bhawanisinghgroup.com" class="email-link">info&#64;bhawanisinghgroup.com <span>↗</span></a><a href="tel:+918219449107" class="phone-link">+91 82194 49107 <span>↗</span></a></div>
<form class="contact-form" (ngSubmit)="submitted = true" #contactForm="ngForm"><div class="form-row"><label>Name <input name="name" required ngModel placeholder="Your name"></label><label>Company <input name="company" ngModel placeholder="Your company or organisation"></label></div><div class="form-row"><label>Email <input type="email" name="email" required ngModel placeholder="you@company.com"></label><label>Phone <span class="optional">Optional</span><input name="phone" ngModel placeholder="Your phone number"></label></div><label>What would you like to discuss? <select name="need" ngModel><option value="">Choose an area</option><option>A website or web app</option><option>A product prototype</option><option>Automation or integration</option><option>Treefy</option><option>Something else</option></select></label><label>Your message <textarea name="description" required ngModel rows="5" placeholder="Tell us about the challenge or opportunity"></textarea></label><button class="button button-primary" type="submit" [disabled]="!contactForm.valid">{{ submitted ? 'Thank you — please email or call to continue' : 'Start a conversation' }} <span>↗</span></button><p class="form-disclaimer">For now, please email or call directly. We are keeping communication personal while BSG grows.</p></form></section>` })
export class ContactPageComponent { submitted = false; }
