import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { services, industries, principles } from '../data/site-data';
import { SectionHeadingComponent } from '../shared/section-heading.component';
import { CtaComponent } from '../shared/cta.component';

@Component({ selector: 'bsg-content-page', standalone: true, imports: [CommonModule, RouterLink, SectionHeadingComponent, CtaComponent], template: `
<section class="page-hero container"><p class="eyebrow">{{ eyebrow }}</p><h1>{{ title }}</h1><p class="page-lead">{{ lead }}</p></section>
<ng-container [ngSwitch]="page">
  <div *ngSwitchCase="'about'" class="container page-body"><bsg-section-heading eyebrow="Who we are" title="An independent company with a longer view." copy="Bhawani Singh Group is founder-led and built with care. We use digital work to help people move forward while creating space for products with a positive purpose." /><div class="manifesto"><p class="eyebrow">Our purpose</p><h2>To make useful things, grow with integrity and leave more good behind us.</h2></div><div class="three-columns"><div><p class="eyebrow">Today</p><p>BSG works directly with people and small businesses that need a clearer, more useful digital presence or product.</p></div><div><p class="eyebrow">Tomorrow</p><p>We are developing purposeful products, starting with Treefy — an idea for better tree care through community participation.</p></div><div><p class="eyebrow">How we work</p><p>We stay curious, communicate honestly and choose practical paths. Every project deserves attention, not inflated promises.</p></div></div><bsg-section-heading eyebrow="What we believe" title="Long-term thinking is a daily practice." /><div class="principle-list"><span *ngFor="let principle of principles"><b>—</b>{{ principle }}</span></div></div>
  <div *ngSwitchCase="'services'" class="container page-body"><bsg-section-heading eyebrow="What we do" title="Focused digital help for work that matters." copy="BSG is a lean, founder-led practice. We take on selected work where a clear outcome and close collaboration can make a real difference." /><div class="detail-list"><article *ngFor="let service of services"><span class="card-index">{{ service.title }}</span><h2>{{ service.value }}</h2><p>{{ service.text }} The tools are chosen around the problem, with a focus on a clean experience and maintainable result.</p><a routerLink="/contact" class="text-link">Discuss this capability <span>→</span></a></article></div></div>
  <div *ngSwitchCase="'products'" class="container page-body"><div class="treefy-intro"><span class="treefy-leaf">✦</span><p class="eyebrow">A BSG product in development</p><h2>Treefy</h2><p class="treefy-tagline">Care for trees. Grow a community.</p><p>Treefy is an early product idea from BSG. Its aim is simple: make tree care easier to organise, recognise the people who show up, and reward volunteers who help trees thrive.</p><p>The product is currently being shaped. We are listening, learning and building deliberately before making promises about features or launch dates.</p><a routerLink="/contact" class="button button-primary">Share an idea for Treefy <span>↗</span></a></div></div>
  <div *ngSwitchCase="'ventures'" class="container page-body"><div class="manifesto"><p class="eyebrow">The group-company vision</p><h2>Build products with focus, then let them grow into their own work.</h2><p>For now, BSG is the single home for our work. As a product proves its value, it may later grow into a focused business with its own identity, team and path to market.</p></div><div class="venture-steps"><div><span>01</span><h3>Notice the need</h3><p>Listen closely to a meaningful problem and the people who experience it.</p></div><div><span>02</span><h3>Make it useful</h3><p>Test, learn and develop a simple answer with care.</p></div><div><span>03</span><h3>Let it grow</h3><p>When the time is right, give a proven product the focus it needs to thrive.</p></div></div></div>
  <div *ngSwitchCase="'industries'" class="container page-body"><bsg-section-heading eyebrow="Who we can help" title="Good digital work starts with listening." copy="We welcome conversations with founders, small businesses and community-minded organisations that have a real problem to solve." /><div class="industry-page-grid"><a *ngFor="let industry of industries" routerLink="/contact"><span>0{{ industries.indexOf(industry) + 1 }}</span><h2>{{ industry }}</h2><b>Start a conversation ↗</b></a></div></div>
  <div *ngSwitchCase="'insights'" class="container page-body"><div class="empty-state"><span class="empty-mark">◎</span><p class="eyebrow">Notes, in time</p><h2>Useful thinking takes time.</h2><p>We are creating a space for practical notes about building products, doing good digital work and growing with purpose. Check back as it develops.</p></div></div>
</ng-container><bsg-cta *ngIf="page !== 'products' && page !== 'insights'" />` })
export class ContentPageComponent implements OnInit {
  page = ''; title = ''; eyebrow = ''; lead = ''; services = services; industries = industries; principles = principles;
  constructor(private route: ActivatedRoute) {}
  ngOnInit(): void { this.page = this.route.snapshot.data['page'] as string; const content: Record<string, [string, string, string]> = { about: ['About BSG', 'Who we are', 'Independent digital work, built patiently for the long term.'], services: ['Services', 'What we do', 'Focused digital support for businesses and ideas with meaningful work to do.'], products: ['Products', 'What we are building', 'Purposeful ideas, given the time and care to become useful.'], ventures: ['Ventures', 'What comes next', 'A long-term ambition to grow focused products into businesses.'], industries: ['Industries', 'Who we can help', 'Digital work that adapts to the people, context and challenge in front of us.'], insights: ['Insights', 'Ideas for moving forward', 'Practical notes on product building, digital work and purposeful growth.'] }; [this.eyebrow, this.title, this.lead] = content[this.page]; }
}
