import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { services, industries, technologies, principles } from '../data/site-data';
import { SectionHeadingComponent } from '../shared/section-heading.component';
import { CtaComponent } from '../shared/cta.component';

@Component({ selector: 'bsg-home', standalone: true, imports: [CommonModule, RouterLink, SectionHeadingComponent, CtaComponent], template: `
<section class="hero container"><div class="hero-copy"><p class="eyebrow">Bhawani Singh Group <span class="dot"></span> Technology, products & ventures</p><h1>Build what matters.<br><em>Make it last.</em></h1><p class="hero-lead">We build technology solutions, digital products and businesses that solve meaningful problems and create lasting value.</p><div class="hero-actions"><a class="button button-primary" routerLink="/contact">Start a conversation <span>↗</span></a><a class="text-link" routerLink="/about">Explore BSG <span>→</span></a></div></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-core"><span>BSG</span><small>01 / BUILDING</small></div><div class="art-label label-one">Technology<br><b>with purpose</b></div><div class="art-label label-two">Est. for<br><b>the long term</b></div></div></section>
<section class="intro section container"><div class="intro-number">01</div><div><p class="eyebrow">A company in motion</p><h2>Technology is the means.<br><span>Meaningful progress is the goal.</span></h2><p class="large-copy">BSGroup is building a technology-driven group of businesses, products and solutions. We partner with organizations today while investing in the ideas and ventures that will shape tomorrow.</p></div></section>
<section class="section dark-section"><div class="container"><bsg-section-heading eyebrow="Our direction" title="Three ways we create value" copy="A clear model for where BSG is today — and where it is going." /><div class="pillar-grid"><article class="pillar"><span>01</span><h3>Build</h3><p>We build software, platforms, applications, integrations and digital solutions around real needs.</p><a routerLink="/services">What we build →</a></article><article class="pillar featured"><span>02</span><h3>Serve</h3><p>We work with businesses to solve technology problems, modernize systems and move important initiatives forward.</p><a routerLink="/services">How we help →</a></article><article class="pillar"><span>03</span><h3>Venture</h3><p>We develop our own products, platforms and future businesses designed to create lasting value.</p><a routerLink="/ventures">Our long view →</a></article></div></div></section>
<section class="section container"><bsg-section-heading eyebrow="Capabilities" title="Engineering that moves business forward" copy="From a focused digital product to a complex enterprise system, we bring practical thinking and disciplined engineering to the work." /><div class="service-grid"><a class="service-card" *ngFor="let service of services.slice(0, 6)" routerLink="/services"><span class="card-index">0{{ services.indexOf(service) + 1 }}</span><h3>{{ service.title }}</h3><p>{{ service.value }}</p><span class="card-arrow">↗</span></a></div><a class="text-link section-link" routerLink="/services">Explore all capabilities <span>→</span></a></section>
<section class="section problem-section"><div class="container split"><div><p class="eyebrow">The problems behind the brief</p><h2>When technology gets in the way, progress slows down.</h2></div><div class="problem-list"><p><span>01</span> Legacy software is holding your business back.</p><p><span>02</span> Your systems do not communicate with each other.</p><p><span>03</span> Manual processes are costing your team time.</p><p><span>04</span> You need a new product, but not a bigger technology burden.</p><p><span>05</span> Your architecture needs a clearer direction.</p></div></div></section>
<section class="section container"><bsg-section-heading eyebrow="How we work" title="Clarity before complexity" copy="Good technology starts with understanding. Our process keeps the work grounded in your users, your goals and your constraints." /><div class="process-grid"><div *ngFor="let item of ['Understand','Discover','Design','Build','Deliver','Evolve']; let i = index"><span>0{{ i + 1 }}</span><h3>{{ item }}</h3><p>{{ ['The business, users, problem and context.','Options, priorities and the right path forward.','The product experience and technical architecture.','The solution with quality and discipline.','Test, deploy, document and hand over.','Improve, learn and scale what works.'][i] }}</p></div></div></section>
<section class="section dark-section tech-section"><div class="container split"><div><p class="eyebrow">Technology & engineering</p><h2>The right tools.<br><em>For the right problem.</em></h2><p class="muted-copy">Technology is never the product by itself. It is the foundation that lets a business serve people better, operate smarter and imagine further.</p><a class="text-link light-link" routerLink="/services">Our engineering approach <span>→</span></a></div><div class="tech-list"><div *ngFor="let group of (technologies | keyvalue)"><span>{{ group.key }}</span><p>{{ group.value.join(' · ') }}</p></div></div></div></section>
<section class="section container"><div class="split"><bsg-section-heading eyebrow="Areas we can serve" title="Different domains. The same focus on useful outcomes." /><div class="industry-cloud"><a *ngFor="let industry of industries" routerLink="/industries">{{ industry }} <span>↗</span></a></div></div></section>
<section class="section future-section"><div class="container future-inner"><div><p class="eyebrow">The long view</p><h2>Today we build solutions.<br><em>Tomorrow, products.</em><br>Over time, businesses.</h2></div><p>Services create relationships and revenue today. Products and ventures give BSG the opportunity to create something of its own — and keep building for the long term.</p></div></section>
<section class="section container principles"><bsg-section-heading eyebrow="Why BSG" title="Ambition, grounded in principles." /><div class="principle-list"><span *ngFor="let principle of principles; let i = index"><b>0{{ i + 1 }}</b>{{ principle }}</span></div></section><bsg-cta />` })
export class HomePageComponent { services = services; industries = industries; technologies = technologies; principles = principles; }
